
services:
  backend:
    build:
      context: ./backend
    expose:
      - "3001"
    environment:
      - OLLAMA_HOST=http://192.168.5.78:11434 # Ollama LXC IP
      - LLM_MODEL=qwen2.5:1.5b                 # llama3.1, qwen2.5:14b, etc.
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
